"""initial schema with indexes

Revision ID: 148eb1fcf1d4
Revises: 
Create Date: 2026-03-30 21:08:58.297383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148eb1fcf1d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_booking_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_booking_groomer_id', ['groomer_id'], unique=False)
        batch_op.create_index('ix_booking_status', ['status'], unique=False)

    with op.batch_alter_table('groomer_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_groomer_city', ['city'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groomer_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_groomer_city')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_status')
        batch_op.drop_index('ix_booking_groomer_id')
        batch_op.drop_index('ix_booking_customer_id')

    # ### end Alembic commands ###
